"""
Changed UserData to UnsplashUserData to remove conflict with UserData table in image-uploader-project. I am deploying the application on the render.com with the same database as the image-uploader project


Revision ID: 0fba84f8167e
Revises: 51fc6c9d02ac
Create Date: 2022-12-20 20:48:35.116413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fba84f8167e'
down_revision = '51fc6c9d02ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
                    sa.Column('username', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'username', name='user_details_pkey')
                    )
    # ### end Alembic commands ###
