"""
Added timestamp to the database

Revision ID: 948377292052
Revises: 
Create Date: 2022-12-17 04:07:08.710833


"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948377292052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
